# Generated by Django 5.2.3 on 2025-06-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fraccion',
            fields=[
                ('nombre_frcc', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_frcc', models.CharField(blank=True, max_length=200, null=True)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('cuota_imp', models.IntegerField(blank=True, null=True)),
                ('cuota_ex', models.IntegerField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'fraccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regulaciones',
            fields=[
                ('nombre_reg', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('desc_reg', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'regulaciones',
                'managed': False,
            },
        ),
    ]
