# Generated by Django 5.2.3 on 2025-06-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('nombre_prov', models.CharField(blank=True, max_length=100, null=True)),
                ('taxid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('domicilio', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
    ]
