# Generated by Django 5.2.3 on 2025-06-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraccionRel',
            fields=[
                ('id_f_r', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fraccion_rel',
                'managed': False,
            },
        ),
    ]
